-- AlterTable
ALTER TABLE `reservations` ADD COLUMN `mercadoPagoPaymentId` VARCHAR(191) NULL,
    ADD COLUMN `mercadoPagoPreferenceId` VARCHAR(191) NULL,
    ADD COLUMN `portalDeclineReason` VARCHAR(191) NULL,
    ADD COLUMN `portalWaConfirmed` BOOLEAN NOT NULL DEFAULT false,
    MODIFY `origin` ENUM('MEMBERSHIP', 'WALK_IN', 'PORTAL', 'PORTAL_REQUEST') NOT NULL,
    MODIFY `status` ENUM('PENDING_APPROVAL', 'CONFIRMED', 'CANCELLED', 'NO_SHOW', 'ATTENDED', 'LATE') NOT NULL DEFAULT 'CONFIRMED';
